name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev
    - name: make
      run: make clean all
    - uses: actions/upload-artifact@v3
      with:
        name: Tanks-Linux
        path: build/bin/*
  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: Start-Process -FilePath ".\setup-sdl2.bat" -ArgumentList $argstr -Wait -NoNewWindow
    - name: make
      run: make clean all
    - uses: actions/upload-artifact@v3
      with:
        name: Tanks-Linux
        path: build/bin/*
